Mahdi/48
mohsen-hassani-org/meraj3 pull request #47
Opened 2022-10-14 12:22 UTC by Mahdikhaloei

2022-10-14 18:41 UTC, mohsen-hassani commented
@Mahdikhaloei, a comment

2022-10-14 18:45 UTC, mohsen-hassani commented on core/permissions.py
> +        if not user == self.request.user:
line 29: `user = self.request.user`
line 34: `if not user == self.request.user:`
isn't it always return False?
@Mahdikhaloei

2022-10-14 18:45 UTC, mohsen-hassani commented on meraj/templates/gentelella/components/rrr_admin.html
> +                                    {% if not rrr.status == statuses.VALID %}
@Mahdikhaloei don't remove, just disable buttons

2022-10-14 18:45 UTC, mohsen-hassani commented on meraj/templates/gentelella/components/rrr_user.html
> +                            <a href="{% if message %}{% url 'meraj_public:delete_rrr' rrr.track_code %}{% else %}{% url 'meraj_public:delete_receipt' rrr.track_code r.id %}{% endif %}" class="btn btn
don't use this approach
a better approach is:
always use meraj_public:delete_receipt url, because this object is always a receipt, then in the related view, check if it's the last receipt in rrr or not
using {% if message %} is a dirty solution and in the future may cause other bugs, since we may have other type of messages in the page

2022-10-21 20:28 UTC, mohsen-hassani commented on meraj/models.py
>          """Check for all Receipts' validation. Return True if all Receipts are valid."""
fix docstring

2022-10-21 20:29 UTC, mohsen-hassani commented on accounts/models.py
> +    def set_stock_holder_id(self):
save stock_holder in this function

2022-10-21 20:31 UTC, mohsen-hassani commented on meraj/models.py
> +        raise NotImplementedError("برای تایید درخواست ابتدا باید همه مدارک تایید شده باشند")
we don't use NotImplementedError for error, either use some of built-in exceptions (Exception, ValidationError, ...) or use a custom exception.
You can also simply return False if the RRR is invalid

2022-10-21 20:34 UTC, mohsen-hassani commented on meraj/templates/gentelella/rrr_details.html
> +<<<<<<< HEAD
fix this

2022-10-21 20:40 UTC, mohsen-hassani commented on meraj/views.py
>          if rrr.receipts.count() == 0:
i think it should be: ```if rrr.receipts.count() == 1:```

2022-10-21 20:41 UTC, mohsen-hassani requested changes
Please check the comments

2022-10-22 05:53 UTC, Mahdikhaloei commented on meraj/views.py
>          if rrr.receipts.count() == 0:
No, in first step the receive is deleted, if the rrr has no receipt the request is deleted.

2022-10-22 06:14 UTC, Mahdikhaloei commented on meraj/models.py
>          """Check for all Receipts' validation. Return True if all Receipts are valid."""
sorry, I do not understand what you mean!!!!!

2022-10-22 06:16 UTC, Mahdikhaloei commented on meraj/models.py
>          """Check for all Receipts' validation. Return True if all Receipts are valid."""
that mean statuses should be status?

2022-10-22 06:18 UTC, Mahdikhaloei commented on accounts/models.py
> +    def set_stock_holder_id(self):
That mean I should save stock_holder_id after giving the value?

2022-10-29 14:02 UTC, merged